### ISSUE TITLE
Produce correct case for EXE and DLL IDs

### ISSUE THREAD

**Issue by AnyOldName3** [symstore/symstore#33]
When using the output of symstore on a case-insensitive file system or webserver, everything works great. However, when using a case-sensitive one, only PDBs will be accessible. This seems to be because Visual Studio queries the presence of EXEs and DLLs with the first eight hex digits of the ID capitalised, and the remainder lowercased. This is visible on AMD's symbol server, for example: https://download.amd.com/dir/bin

Hopefully this is a relatively easy fix and can make it into a patch release soon.

**Comment by elmjag** [comment]
Which version of symstore are you using?

This bug should be fixed in symstore v0.3.4  https://github.com/symstore/symstore/issues/25

I did test publishing two DLL from AMD's symbol server using symstore version 0.3.4

https://download.amd.com/dir/bin/amdhdl32.dll/58C315C32d000/
https://download.amd.com/dir/bin/libamdsmi_host.dll/64D630D97f000/

The cases look correct to me:
    
    
    bin
    ├── 000Admin
    │   ├── 0000000001
    │   ├── history.txt
    │   ├── lastid.txt
    │   └── server.txt
    ├── amdhdl32.dll
    │   └── 58C315C32d000
    │       └── amdhdl32.dll
    ├── libamdsmi_host.dll
    │   └── 64D630D97f000
    │       └── libamdsmi_host.dll
    └── pingme.txt

**Comment by AnyOldName3** [comment]
0.3.3, apparently. I thought I'd got the CI script I was using it in set to grab the latest version, but apparently I'd pinned it to what was the latest the last time I touched it, and somehow never actually needed to pull binaries from the server until now. Sorry for the noise.
